# Generated by Django 5.0.7 on 2024-08-19 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='default.jpg', upload_to='profile_pics')),
                ('phone', models.CharField(default='080-', max_length=11)),
                ('site_name', models.CharField(default='EagleWings', max_length=225)),
            ],
        ),
    ]
